### ISSUE TITLE
Evasion or poison?

### ISSUE THREAD

**Issue by likuanppd** [Mark12Ding/GNN-Practical-Attack#1]
Hi Ding！

It it written in your paper"Our work belongs to untargeted evasion attacks" To my knowledge, evasion means that train the model on clean data then test after attack.But I find you train on a perturbed graph after attack(select nodes and inject perturbation), so i guess GC-RWCS might be poison attack?

Look forward to your reply.

**Comment by jiaqima** [comment]
Hello. We clarify that the GNN model is trained on *clean data* in our case. 

Perhaps the layout of main.py is a little bit misleading. The node selection step is done before the model training but we do not inject perturbation in the node selection step. So the data is still the clean data when we train the model.
