### ISSUE TITLE
blackbox?

### ISSUE THREAD

**Issue by gitdawn123** [Mark12Ding/GNN-Practical-Attack#2]
hello，
I read this paper recently，there is a doubt that whats your blackbox settings?
in the attack code ,you have used the label information of the trainset to get the loss,but i think  It's forbidden in blackbox.
It's a good work to select nodes,but i want to konw how you implement  the black attack.
can you tell me more details about it?
thank you!

**Comment by jiaqima** [comment]
Thanks for your interest. First we would like to clarify that the selection of nodes only depends on the graph so this step is purely black-box. In our experiments, the loss was used in the second step when constructing the perturbation epsilon. 

And as we explained in the "Nuisance parameters of the attack procedure" paragraph at the end of page 7 of our paper, the use of loss is at a very coarse level to mimic the semantic knowledge we might have about the features of a real-world task. We did assume that, to perform attack in practice, the attacker should have rough knowledge about which features are important to the task (e.g., the gender of a person might be an important feature affecting the recommendation to that user). 

For the experiments in our paper, we found recently (after our publication) that we can actually further limit the use of the loss information. We find that we can use the loss of a GCN model to construct the perturbation vector epsilon and use this perturbation vector to attack GAT or JKNet trained independently to the GCN, and still see significant performance drops in the GAT and JKNet. 

Hope this comment answers your questions.

**Comment by gitdawn123** [comment]
@jiaqima 
Thank you for your patient explanation.
I solved my doubts after reading your answer.
At last,you mean  the attack results  are  transferable? 
In short，your paper and answers have inspired me a lot.
thanks.

**Comment by jiaqima** [comment]
> @jiaqima
> Thank you for your patient explanation.
> I solved my doubts after reading your answer.
> At last,you mean the attack results are transferable?
> In short，your paper and answers have inspired me a lot.
> thanks.

Glad to hear that. 

For my last point, you can understand it as the attack is transferable. And at the same time, this implies that one doesn't really need much information about the victim GNN model to perform effective attack.

Closing this issue for now.
