### ISSUE TITLE
DOUBT ABOUT RWCS

### ISSUE THREAD

**Issue by gitdawn123** [Mark12Ding/GNN-Practical-Attack#3]
hello，
in paper，you said 'The difference between RWCS and PageRank is that the latter uses the stationary transition matrix M for a random walk with restart.'
it means   in RWCS   Mij=1/di    but in PageRank Mij=1  if (i,j) ∈ E，right？
Can you explain it in detail？
thank you！

**Comment by jiaqima** [comment]
Please see the following article for more details about the relationship between PageRank and random walk.

https://www.math.ucsd.edu/~fan/wp/lov.pdf

**Comment by gitdawn123** [comment]
thank you.
